# -*- coding: utf-8 -*-
"""Netflix :Business case

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MX08ETacyNfeR98ts7QuzA_NCcXuNsy2
"""

!gdown https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/000/940/original/netflix.csv

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('netflix.csv')

data.head()

data.shape

data.describe()

data.info()

movies = data.loc[df['type'] == 'Movie']
movies

tvshows = data.loc[df['type']=="TV Show"]
tvshows

data['type'].value_counts()["Movie"]

data['type'].value_counts()["TV Show"]

""". There are singnificantly more movies as compared to tv shows."""

data['rating'].unique()

data['rating'].value_counts()

"""

* This shows that movies and tv shows with rating TV-MA are more liked by people.

"""

movies['rating'].value_counts()['TV-MA']

tvshows['rating'].value_counts()['TV-MA']

"""

*  This shows that movie with rating 'TV-MA' are more liked and watched by people than tv shows with the same rating.

"""

movies_per_year = movies.groupby('release_year').size()
movies_per_year.tail(20)

"""

*   This shows that  no. of movies released in the past 2 decades.

*   The year 2017 and 2018 has the most no. of movie release.



"""

tvshows_per_year = tvshows.groupby('release_year').size()
tvshows_per_year.tail(20)

"""

*   This shows that the number of tv shows released over past 2 decades.

*   The year 2018 and 2020 has most number of movie release.

*   This also shows that netflix is more focused on movies  more than tvshows.

"""

movies['director'].value_counts()

movies['cast'].value_counts()

tvshows['director'].value_counts()

tvshows['cast'].value_counts()

movies['country'].value_counts()

tvshows['country'].value_counts()

"""

*   Comparing the data , it clearly shows that the united state has most access to most movies followed by india.
* As for tvshow united state has most access to most movie follwed by united kingdom.

"""

movies['date_added'].value_counts()

tvshows['date_added'].value_counts()

movies['duration'].value_counts()

movies['listed_in'].value_counts()

plt.figure(figsize=(10,6))
sns.histplot(data['rating'])
plt.title('Distributon of ratings')
plt.xticks(rotation=90)
plt.show()

missing_values = data.isnull().sum()
missing_values

continuous_vars = ['duration', 'rating', 'release_year']

for var in continuous_vars:
# Distplot
 sns.displot(data[var], kde=True)
 plt.title(f"Distribution of {var}")
 plt.show()

# Countplot
sns.countplot(data[var])
plt.title(f"Countplot of {var}")
plt.show()

#hisplot
sns.histplot(data[var])
plt.title(f"Histogram of {var}")
plt.show()

correlation_matrix = data.select_dtypes(include=np.number).corr()

#heatmap

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

#pairplot
sns.pairplot(data.select_dtypes(include=np.number))
plt.show()

"""So far we have performed a lot of operations over the dataset to digout some very useful informationfrom it.
1. Netflix has more Movies than TV shows.
2. Most number of Movies and TV shows are produced by United States, followed by India.
3. Most of the content of Netflix is for Mature audience.
4. 2018 is the year in which Netflix released a lot of content as compared to other years.
5. International Movies and Dramas are the most popular Genres on Netflix followed by Documentaries.
6. Visualization showed the exponential increase in the content release over the past years.
"""